name: Npm deployment

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest

    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: make dep

      - name: Bundle
        run: yarn bundle

      - name: Publish to registry
        uses: blocklet/action-upload@v0.1.6
        with:
          endpoint: ${{ secrets.STAGING_REGISTRY }}
          developer-sk: ${{ secrets.ABTNODE_DEV_STAGING_SK }}

      - name: Deploy to abtnode
        uses: blocklet/action-deploy@v0.1.2
        with:
          endpoint: ${{ secrets.STAGING_NODE_ENDPOINT }}
          access-key: ${{ secrets.STAGING_NODE_ACCESS_KEY }}
          access-secret: ${{ secrets.STAGING_NODE_ACCESS_SECRET }}
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}

      - name: Release to Github
        uses: blocklet/action-release-to-github@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
